# Generated by Django 4.1.3 on 2022-12-28 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUsuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteo',
            name='fecha_posteo_imagen',
            field=models.DateField(auto_now_add=True),
        ),
    ]
