# Generated by Django 4.1.3 on 2022-12-28 01:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppUsuarios', '0002_alter_posteo_fecha_posteo_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteo',
            name='contenido_posteo',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
