# Generated by Django 4.1.3 on 2022-12-28 01:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppUsuarios', '0003_alter_posteo_contenido_posteo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteo',
            name='contenido_posteo',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
