# Generated by Django 4.1.3 on 2022-12-28 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUsuarios', '0005_alter_posteo_imagen_posteo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posteo',
            name='imagen_posteo',
        ),
        migrations.AddField(
            model_name='posteo',
            name='imagen_post',
            field=models.ImageField(default=0, upload_to='posteos'),
            preserve_default=False,
        ),
    ]
