# Generated by Django 4.1.3 on 2022-12-28 04:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppUsuarios', '0007_alter_posteo_fecha_posteo_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteo',
            name='fecha_posteo_imagen',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
