# Generated by Django 4.1.3 on 2022-12-28 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUsuarios', '0008_alter_posteo_fecha_posteo_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteo',
            name='fecha_posteo_imagen',
            field=models.DateField(blank=True, null=True),
        ),
    ]
