# Generated by Django 4.1.3 on 2022-12-31 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppUsuarios', '0010_imagenperfil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImagenPerfil',
        ),
    ]
