# Generated by Django 4.1.3 on 2023-01-04 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUsuarios', '0016_alter_posteo_subtitulo_posteo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteo',
            name='subtitulo_posteo',
            field=models.CharField(default='hola', max_length=40),
        ),
    ]
