# Generated by Django 4.1.3 on 2023-01-05 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUsuarios', '0017_alter_posteo_subtitulo_posteo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteo',
            name='imagen_post',
            field=models.ImageField(blank=True, upload_to='posteos'),
        ),
    ]
