# Generated by Django 4.1.3 on 2023-01-04 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppUsuarios', '0020_alter_posteo_subtitulo_posteo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posteo',
            name='subtitulo_posteo',
        ),
    ]
