# Generated by Django 4.1.3 on 2023-01-04 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUsuarios', '0021_remove_posteo_subtitulo_posteo'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteo',
            name='subtitulo_posteo',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
