# Generated by Django 4.1.3 on 2023-01-05 01:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppUsuarios', '0027_chat_delete_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='tiempo',
            field=models.DateField(default=django.utils.timezone.now, verbose_name=models.DateField(auto_now_add=True)),
            preserve_default=False,
        ),
    ]
