# Generated by Django 4.1.3 on 2023-01-05 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUsuarios', '0028_alter_chat_tiempo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='tiempo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
