# Generated by Django 4.1.3 on 2023-01-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUsuarios', '0029_alter_chat_tiempo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='tiempo',
            field=models.DateField(auto_now_add=True),
        ),
    ]
