# Generated by Django 4.1.3 on 2023-01-06 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUsuarios', '0030_alter_chat_tiempo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='tiempo',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
