# Generated by Django 4.1.3 on 2023-01-06 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppUsuarios', '0018_alter_posteo_imagen_post'),
        ('AppUsuarios', '0031_alter_chat_tiempo'),
    ]

    operations = [
    ]
