# Generated by Django 4.1.3 on 2023-01-06 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppUsuarios', '0032_merge_20230105_2232'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
