# Generated by Django 4.1.3 on 2023-01-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUsuarios', '0033_delete_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteo',
            name='subtitulo2_posteo',
            field=models.CharField(default='Pais', max_length=40),
        ),
        migrations.AlterField(
            model_name='posteo',
            name='subtitulo_posteo',
            field=models.CharField(default='Provincia', max_length=40),
        ),
    ]
