# Generated by Django 4.1.3 on 2023-01-07 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppUsuarios', '0035_biografia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biografia',
            old_name='usuario',
            new_name='usuarioBio',
        ),
    ]
