# Generated by Django 4.1.3 on 2023-01-08 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppUsuarios', '0037_alter_biografia_bio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Biografia',
        ),
    ]
